// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://fymbknnagfylbzbtffap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5bWJrbm5hZ2Z5bGJ6YnRmZmFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNzg4MDMsImV4cCI6MjA2OTg1NDgwM30.7atUFGNIUeOLUPGls3c_TXNmuFQQcHMIxhcj84Euuz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);